from __future__ import annotations

from pathlib import Path

from pptx import Presentation
from pptx.util import Inches, Pt


def export_fallback_pptx(
    *,
    project_name: str,
    normalized_bundle_path: Path,
    output_path: Path,
) -> Path:
    """Create a simple PPTX from normalized markdown as a service fallback.

    This is a transitional export path for the service MVP before the full
    SVG/Executor pipeline is connected to the backend worker.
    """
    presentation = Presentation()

    title_layout = presentation.slide_layouts[0]
    title_slide = presentation.slides.add_slide(title_layout)
    title_slide.shapes.title.text = project_name
    title_slide.placeholders[1].text = "Generated by PPT Master Service MVP fallback exporter"

    content_layout = presentation.slide_layouts[1]
    content = normalized_bundle_path.read_text(encoding="utf-8", errors="replace")
    sections = _split_sections(content)

    for section_title, section_body in sections:
        slide = presentation.slides.add_slide(content_layout)
        slide.shapes.title.text = section_title
        text_frame = slide.placeholders[1].text_frame
        text_frame.clear()

        lines = [line.strip() for line in section_body.splitlines() if line.strip()]
        if not lines:
            lines = ["No normalized content available."]

        for index, line in enumerate(lines[:12]):
            paragraph = text_frame.paragraphs[0] if index == 0 else text_frame.add_paragraph()
            paragraph.text = line[:240]
            paragraph.level = 0 if index == 0 else 1
            paragraph.font.size = Pt(18 if index == 0 else 14)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    presentation.save(str(output_path))
    return output_path


def _split_sections(content: str) -> list[tuple[str, str]]:
    sections: list[tuple[str, str]] = []
    title: str | None = None
    body_lines: list[str] = []

    for line in content.splitlines():
        if line.startswith("## "):
            if title is not None:
                sections.append((title, "\n".join(body_lines).strip()))
            title = line[3:].strip()
            body_lines = []
            continue
        body_lines.append(line)

    if title is not None:
        sections.append((title, "\n".join(body_lines).strip()))

    if not sections:
        sections.append(("Normalized Sources", content.strip()))
    return sections